// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSY-vOGQTXXpUUNicD3NNOtmOxFtyKKU4',
    appId: '1:514079644073:web:4bc0bc5d1cf57b6a4b8cb8',
    messagingSenderId: '514079644073',
    projectId: 'foreach-todo-1311b',
    authDomain: 'foreach-todo-1311b.firebaseapp.com',
    databaseURL: 'https://foreach-todo-1311b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foreach-todo-1311b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEhjfQk3Ru2HswCVOoVJshiBLDCRqKxOU',
    appId: '1:514079644073:android:c8e06c115b443f434b8cb8',
    messagingSenderId: '514079644073',
    projectId: 'foreach-todo-1311b',
    databaseURL: 'https://foreach-todo-1311b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foreach-todo-1311b.appspot.com',
  );
}
